import assert from 'node:assert/strict';
import {evidenceInFolder,evidenceForExport,moveEvidenceItems,unfileEvidenceFolder,evidenceMarkdown} from '../web/markdown.js';
const old=[{id:'28:353',speaker:'You',text:'"Behind the blue door."',conversation:28,title:'GARTE MAIN'},{id:'28:765',speaker:'Garte',text:'"Good for you."',conversation:28,title:'GARTE MAIN'},{id:'381:13',speaker:'Measurehead',text:'"AREOPAGITES."',conversation:381,title:'GATES'}];
assert.equal(evidenceInFolder(old,'').length,3,'Legacy evidence must remain visible in Unfiled');
const moved=moveEvidenceItems(old,new Set(['28:353','28:765']),'history');
assert.deepEqual(old.map(n=>n.folderId),[undefined,undefined,undefined],'Moving must preserve the original evidence objects');
assert.deepEqual(evidenceInFolder(moved,'history').map(n=>n.id),['28:353','28:765']);
assert.deepEqual(evidenceForExport(moved,'all',new Set(['381:13'])).map(n=>n.id),['381:13']);
assert.deepEqual(evidenceForExport(moved,'history',new Set()).map(n=>n.id),['28:353','28:765']);
assert.equal(evidenceForExport(moved,'history',new Set(['381:13'])).length,0,'Hidden selections must not leak into folder exports');
const unfiled=unfileEvidenceFolder(moved,'history');
assert.equal(evidenceInFolder(unfiled,'').length,3,'Deleting a folder must retain every snippet');
assert.deepEqual(unfiled.map(n=>n.text),old.map(n=>n.text));
const markdown=evidenceMarkdown(evidenceForExport(moved,'history',new Set(['28:353'])));
assert.ok(markdown.includes('[28:353]'));
assert.ok(!markdown.includes('[28:765]'));
assert.ok(!markdown.includes('[381:13]'));
assert.equal(evidenceMarkdown(old).split('- - -').length,2);
console.log('Evidence migration, folder moves, folder deletion, and scoped Markdown export checks passed.');
