export function initPresetPanel({api,icon}){
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let state=null,currentId=null,draft=null;const drafts=new Map();
  const button=document.createElement('button');button.type='button';button.className='appearance';button.id='presets-open';button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-expanded','false');button.innerHTML=icon('book-open')+' <span>Presets</span>';
  const actions=document.createElement('div');actions.className='header-actions';const reading=document.querySelector('#reading-open');reading.before(actions);actions.append(button,reading);
  const panel=document.createElement('dialog');panel.id='preset-panel';panel.setAttribute('aria-labelledby','preset-panel-title');panel.innerHTML=`<div class="dialog-top"><h2 id="preset-panel-title">Prompt presets</h2><button type="button" class="close" aria-label="Close presets">${icon('x')}</button></div><label>Active preset<select id="preset-select"></select></label><div class="preset-actions"><button type="button" class="secondary" id="preset-create">New preset</button><button type="button" class="text-button" id="preset-delete">Delete preset</button></div><p class="dialog-note">Save edits to use them in new responses. Earlier responses keep their original prompt.</p><div id="preset-editor"></div><details class="preset-preview"><summary>Preview assembled prompt</summary><label>Mode<select id="preset-preview-mode"><option value="research">Archive research</option><option value="chat">No search</option></select></label><pre id="preset-preview-text"></pre></details><div class="preset-save-row"><button type="button" class="primary" id="preset-save">Save preset</button><p id="preset-feedback" role="status" aria-live="polite"></p></div>`;
  document.body.append(panel);const $=s=>panel.querySelector(s);
  $('.close').onclick=()=>panel.close();panel.onclose=()=>button.setAttribute('aria-expanded','false');
  function capture(){
    if(!draft)return;
    draft.name=$('#preset-name').value;draft.mainPrompt=$('#preset-main').value;draft.chatPrompt=$('#preset-chat').value;
    panel.querySelectorAll('[data-block]').forEach((row,i)=>{draft.blocks[i]={...draft.blocks[i],title:row.querySelector('[data-title]').value,content:row.querySelector('[data-content]').value,enabled:row.querySelector('[data-enabled]').checked,scope:row.querySelector('[data-scope]').value};});
    drafts.set(currentId,structuredClone(draft));preview();
  }
  function preview(){if(!draft)return;const mode=$('#preset-preview-mode').value;$('#preset-preview-text').textContent=[mode==='chat'?draft.chatPrompt:draft.mainPrompt,...draft.blocks.filter(b=>b.enabled&&(b.scope==='both'||b.scope===mode)).map(b=>b.content)].filter(Boolean).join('\n\n');}
  function renderEditor(){
    $('#preset-editor').innerHTML=`<label>Preset name<input id="preset-name" maxlength="80" value="${escape(draft.name)}"></label><label>Main research prompt<textarea id="preset-main" rows="9" maxlength="24000">${escape(draft.mainPrompt)}</textarea></label><details><summary>No-search main prompt</summary><label class="sr-only" for="preset-chat">No-search main prompt</label><textarea id="preset-chat" rows="5" maxlength="12000">${escape(draft.chatPrompt)}</textarea></details><div class="section-heading"><h3>Prompt blocks</h3><button type="button" class="text-button" id="preset-add-block">Add block</button></div><div id="preset-blocks">${draft.blocks.map((b,i)=>`<section class="prompt-block" data-block="${i}"><div class="prompt-block-top"><label><input type="checkbox" data-enabled ${b.enabled?'checked':''}> Enabled</label><div><button type="button" class="text-button block-up" data-index="${i}" aria-label="Move block up" ${i===0?'disabled':''}>${icon('chevron-up')}</button><button type="button" class="text-button block-down" data-index="${i}" aria-label="Move block down" ${i===draft.blocks.length-1?'disabled':''}>${icon('chevron-up')}</button><button type="button" class="text-button block-remove" data-index="${i}" aria-label="Remove block">${icon('trash-2')}</button></div></div><label>Block name<input data-title maxlength="80" value="${escape(b.title)}"></label><label>Apply to<select data-scope>${[['both','Both modes'],['research','Archive research'],['chat','No search']].map(([value,label])=>`<option value="${value}" ${b.scope===value?'selected':''}>${label}</option>`).join('')}</select></label><label>Instructions<textarea data-content rows="5" maxlength="12000">${escape(b.content)}</textarea></label></section>`).join('')}</div>`;
    $('#preset-add-block').onclick=()=>{capture();if(draft.blocks.length>=32){$('#preset-feedback').textContent='Use up to 32 blocks.';return;}draft.blocks.push({id:crypto.randomUUID?.()||String(Date.now()),title:'Prompt block',content:'',enabled:true,scope:'both'});renderEditor();capture();$('#preset-blocks').lastElementChild.querySelector('[data-title]').focus();};
    panel.querySelectorAll('.block-remove,.block-up,.block-down').forEach(b=>b.onclick=()=>{capture();const i=Number(b.dataset.index);if(b.classList.contains('block-remove'))draft.blocks.splice(i,1);else{const next=i+(b.classList.contains('block-up')?-1:1);[draft.blocks[i],draft.blocks[next]]=[draft.blocks[next],draft.blocks[i]];}renderEditor();capture();});
    $('#preset-editor').oninput=()=>{capture();$('#preset-feedback').textContent='Unsaved changes.';};preview();
  }
  function selectDraft(id){currentId=id;draft=structuredClone(drafts.get(id)||state.presets.find(p=>p.id===id));renderEditor();$('#preset-feedback').textContent=drafts.has(id)?'Unsaved changes.':'';}
  function renderState(){const select=$('#preset-select');select.replaceChildren(...state.presets.map(p=>new Option(p.name,p.id)));select.value=state.activeId;button.title='Preset: '+state.presets.find(p=>p.id===state.activeId)?.name;$('#preset-delete').disabled=state.presets.length===1;selectDraft(state.activeId);}
  async function refresh(){state=await api('presets');renderState();return state;}
  button.onclick=async()=>{try{if(panel.open){panel.close();return;}await refresh();panel.showModal();button.setAttribute('aria-expanded','true');}catch(e){window.alert(e.message);}};
  $('#preset-select').onchange=async()=>{capture();try{state=await api('presets/manage',{action:'select',id:$('#preset-select').value});renderState();}catch(e){$('#preset-feedback').textContent=e.message;}};
  $('#preset-preview-mode').onchange=preview;
  $('#preset-save').onclick=async()=>{capture();const save=$('#preset-save');save.disabled=true;try{state=await api('presets/manage',{action:'save',id:currentId,preset:draft});drafts.delete(currentId);renderState();$('#preset-feedback').textContent='Preset saved.';}catch(e){$('#preset-feedback').textContent=e.message;}finally{save.disabled=false;}};
  $('#preset-create').onclick=async()=>{capture();try{state=await api('presets/manage',{action:'create',preset:{...draft,name:draft.name+' copy'}});renderState();$('#preset-feedback').textContent='New preset created.';}catch(e){$('#preset-feedback').textContent=e.message;}};
  $('#preset-delete').onclick=async()=>{if(!confirm('Delete preset “'+draft.name+'”?'))return;try{const removed=currentId;state=await api('presets/manage',{action:'delete',id:removed});drafts.delete(removed);renderState();}catch(e){$('#preset-feedback').textContent=e.message;}};
  return {refresh,get id(){return state?.activeId;}};
}
